name = "popkg"
uuid = "8a25b231-4c67-41ef-84f9-ed27388934cc"
authors = ["Haloxxx"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
